# Generated by Django 5.0.6 on 2025-03-19 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgboard', '0002_plainuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BadUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(unique=True)),
                ('password', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='PlainUser',
        ),
        migrations.AddField(
            model_name='badmessage',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msgboard.baduser'),
        ),
    ]
